# gradio_app.py
import gradio as gr
import asyncio
from research_manager import ResearchManager
from email_agent import send_email
import os
from dotenv import load_dotenv

load_dotenv()

async def run_research(query: str, send_email_option: bool, progress=gr.Progress()):
    """Run research and optionally send email"""
    if not query or query.strip() == "":
        return "❌ Please enter a research query.", ""
    
    try:
        # Update progress
        progress(0.1, desc="Planning research...")
        
        # Run research
        rm = ResearchManager()
        progress(0.3, desc="Executing searches...")
        
        result = await rm.run(query)
        
        progress(0.9, desc="Finalizing report...")
        
        # Format the result
        formatted_result = f"# Research Results\n\n**Query:** {query}\n\n---\n\n{result}"
        
        email_status = ""
        
        # Send email if requested
        if send_email_option:
            progress(0.95, desc="Sending email...")
            
            # Check if SendGrid API key is set
            if not os.getenv("SENDGRID_API_KEY"):
                email_status = "\n\n⚠️ Email not sent: SENDGRID_API_KEY not configured in .env file"
            else:
                try:
                    # Create HTML version of the report
                    html_body = f"""
                    <html>
                    <head>
                        <style>
                            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
                            h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
                            h2 {{ color: #34495e; margin-top: 25px; }}
                            .query {{ background: #ecf0f1; padding: 15px; border-left: 4px solid #3498db; margin: 20px 0; }}
                            .content {{ white-space: pre-wrap; }}
                            .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 0.9em; }}
                        </style>
                    </head>
                    <body>
                        <h1>🔬 AI Research Report</h1>
                        <div class="query">
                            <strong>Research Query:</strong><br>
                            {query}
                        </div>
                        <div class="content">
                            {result.replace(chr(10), '<br>')}
                        </div>
                        <div class="footer">
                            Generated by AI Research System
                        </div>
                    </body>
                    </html>
                    """
                    
                    subject = f"Research Report: {query[:50]}{'...' if len(query) > 50 else ''}"
                    send_email(subject, html_body)
                    email_status = "\n\n✅ Email sent successfully!"
                except Exception as e:
                    email_status = f"\n\n❌ Email failed: {str(e)}"
        
        progress(1.0, desc="Complete!")
        
        return formatted_result + email_status, formatted_result
        
    except Exception as e:
        return f"❌ Error: {str(e)}", ""


def run_research_sync(query: str, send_email_option: bool, progress=gr.Progress()):
    """Synchronous wrapper for async research function"""
    return asyncio.run(run_research(query, send_email_option, progress))


# Create Gradio interface
with gr.Blocks(title="Deep Research") as app:
    gr.Markdown(
        """
        # 🔬 Deep Research
        ### AI-Powered Research Assistant
        Enter your research query below and let our AI agents conduct comprehensive research for you.
        """
    )
    
    with gr.Row():
        with gr.Column():
            query_input = gr.Textbox(
                label="What topic would you like to research?",
                placeholder="e.g., What are some of the most exciting commercial applications of Autonomous Agentic AI as of April 2025",
                lines=3,
                max_lines=5
            )
            
            send_email_checkbox = gr.Checkbox(
                label="Send results via email",
                value=False,
                info="Email will be sent to the address configured in your .env file"
            )
            
            run_button = gr.Button("Run", variant="primary", size="lg")
    
    with gr.Row():
        output_display = gr.Markdown(label="Results")
    
    with gr.Row():
        download_output = gr.Textbox(
            label="Download Report",
            visible=False,
            interactive=False
        )
        download_button = gr.DownloadButton(
            label="📥 Download Report as Text",
            visible=False
        )
    
    # Event handlers
    def show_download(result, formatted):
        if formatted and formatted.strip():
            return {
                download_output: gr.update(value=formatted, visible=True),
                download_button: gr.update(visible=True, value="research_report.txt")
            }
        return {
            download_output: gr.update(visible=False),
            download_button: gr.update(visible=False)
        }
    
    run_button.click(
        fn=run_research_sync,
        inputs=[query_input, send_email_checkbox],
        outputs=[output_display, download_output]
    ).then(
        fn=show_download,
        inputs=[output_display, download_output],
        outputs=[download_output, download_button]
    )
    
    # Examples
    gr.Examples(
        examples=[
            ["Latest approaches to autonomous navigation for visually impaired people 2024"],
            ["What are the most promising renewable energy technologies in 2025?"],
            ["Current state of quantum computing applications in cryptography"],
            ["Emerging trends in personalized medicine and genomics"],
        ],
        inputs=query_input,
        label="Example Research Queries"
    )
    
    gr.Markdown(
        """
        ---
        ### 💡 How it works:
        1. **Planning**: AI creates a research plan with multiple search queries
        2. **Searching**: Executes searches in parallel using multiple AI agents
        3. **Writing**: Aggregates results into a comprehensive summary
        4. **Email** (optional): Sends formatted report to your email
        
        ### ⚙️ Configuration:
        - Models: `openai/gpt-4o-mini` via OpenRouter
        - Email: SendGrid (configure `SENDGRID_API_KEY` in `.env`)
        - API Key: OpenRouter (configure `OPENROUTER_API_KEY` in `.env`)
        """
    )

if __name__ == "__main__":
    print("Starting Deep Research Gradio App...")
    print("Email feature:", "Enabled" if os.getenv("SENDGRID_API_KEY") else "Disabled (SENDGRID_API_KEY not set)")
    app.launch(
        server_name="0.0.0.0",
        server_port=7680,
        share=True,
        show_error=True
    )
